---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/vplugin/test/test"
type: Opaque
stringData:
  username: <username>
  password: <password>
